name = "SpinePeriods"
uuid = "163584a9-52e1-4a4e-9262-a8c2d5456af4"
authors = ["Jody Dillon <jody.dillon@energyreform.ie>", "Manuel Marin <manuelma@kth.se>"]
version = "0.1.0"

[deps]
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
SpineInterface = "0cda1612-498a-11e9-3c92-77fa82595a4f"
SpineOpt = "0d8fc150-4032-4b6e-9540-20efcb304861"
URIParser = "30578b45-9adc-5946-b283-645ec420af67"

[compat]
JuMP = "0.21.2"
julia = "^1.2"
